Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
#training the Logistic Regression Model with Training Data
from sklearn.linear_model import LogisticRegression # make sure to import the necessary module

model = LogisticRegression() # define the model variable in the current scope
model.fit(X_train, Y_train)
from sklearn.metrics import accuracy_score

In [ ]:
#loading the dataset to a pandas Dataframe
#loading the dataset to a pandas Dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv', on_bad_lines='skip') # skip lines with errors

<ipython-input-7-6280343b4fdc>:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  credit_card_data = pd.read_csv('/content/creditcard.csv', on_bad_lines='skip') # skip lines with errors

In [ ]:
# first 5 rows of the dataFrame
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
255083,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0.0
255084,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0.0
255085,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0.0
255086,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0.0
255087,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0.0

In [ ]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255088 entries, 0 to 255087
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    255088 non-null  float64
 1   V1      255088 non-null  float64
 2   V2      255088 non-null  float64
 3   V3      255088 non-null  float64
 4   V4      255088 non-null  float64
 5   V5      255088 non-null  float64
 6   V6      255088 non-null  float64
 7   V7      255088 non-null  float64
 8   V8      255088 non-null  float64
 9   V9      255088 non-null  float64
 10  V10     255088 non-null  object
 11  V11     255087 non-null  float64
 12  V12     255086 non-null  float64
 13  V13     255086 non-null  float64
 14  V14     255086 non-null  float64
 15  V15     255086 non-null  float64
 16  V16     255085 non-null  float64
 17  V17     255085 non-null  float64
 18  V18     255085 non-null  float64
 19  V19     255085 non-null  float64
 20  V20     255085 non-null  float64
 21  V21     255085 non-null  float64
 22  V22     255085 non-null  float64
 23  V23     255084 non-null  float64
 24  V24     255084 non-null  float64
 25  V25     255084 non-null  float64
 26  V26     255083 non-null  float64
 27  V27     255083 non-null  float64
 28  V28     255083 non-null  float64
 29  Amount  255083 non-null  float64
 30  Class   255083 non-null  float64
dtypes: float64(30), object(1)
memory usage: 60.3+ MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       2
V13       2
V14       2
V15       2
V16       3
V17       3
V18       3
V19       3
V20       3
V21       3
V22       3
V23       4
V24       4
V25       4
V26       5
V27       5
V28       5
Amount    5
Class     5
dtype: int64

In [ ]:
# distribution of legit transactions & fruad transactions
credit_card_data['Class'].value_counts()

Class
0.0    254660
1.0       423
Name: count, dtype: int64

This Dataset is highly unbalanced

0--> Normal Transaction

1-->fraud transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(254660, 31)
(423, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    254660.000000
mean         86.470305
std         248.525667
min           0.000000
25%           5.350000
50%          20.660000
75%          75.000000
max       25691.160000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     423.000000
mean      124.969976
std       266.541889
min         0.000000
25%         1.000000
50%         7.570000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions
#compare the values for both transactions
credit_card_data.groupby('Class').mean(numeric_only=True) # set numeric_only to True to only calculate the mean of numeric columns

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,101711.881579,0.033815,0.006483,-0.063520,-0.022767,0.040774,-0.008487,0.020277,-0.009494,0.029367,...,-0.007252,0.000005,0.009253,0.004731,-0.000706,-0.017152,-0.001698,-0.000295,-0.000590,86.470305
1.0,87810.397163,-4.276283,3.400701,-6.668589,4.377175,-2.642163,-1.276407,-5.142759,-0.012933,-2.309489,...,0.385635,0.604462,0.049255,-0.008117,-0.152212,-0.001014,0.041191,0.158276,0.086922,124.969976

Under-Sample

Build a sample dataset containing similar distribution of normal transactins and Fraud Tranasactions

Number of transactions-->25

In [ ]:
legit_sample = legit.sample(n=25)

Containing two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
13455,10262.0,-1.161678,1.014845,1.341105,0.219589,-0.399681,-0.792609,0.060908,0.450452,0.744772,...,-0.290013,-0.735224,0.328666,0.410629,-0.247836,0.007369,0.006379,0.007010,19.98,0.0
193359,143238.0,-0.905777,1.242481,-0.716030,-0.646550,0.479189,-0.939751,0.273707,0.552560,-0.567054,...,0.407173,0.937074,-0.300562,0.729079,0.234039,-0.196718,-0.288665,-0.142388,1.79,0.0
139260,119470.0,-0.643736,-0.178902,-0.279128,-0.806155,1.804098,1.499641,0.597049,0.239050,0.243199,...,-0.102520,0.244553,0.544099,-0.592483,-1.084877,0.176266,-0.348630,-0.235414,32.80,0.0
191141,142327.0,-0.679435,0.618923,1.194657,-0.425657,-2.250719,0.751678,-0.570801,-3.343568,-0.617492,...,2.325145,-2.408189,0.156442,0.292784,1.115726,-0.234767,0.407610,0.109090,208.62,0.0
104104,80542.0,1.104597,-0.277470,1.231644,0.634464,-1.254868,-0.380660,-0.761793,0.227249,0.548320,...,0.134066,0.261670,0.036225,0.522854,0.071286,0.323604,-0.008937,0.022038,29.05,0.0

In [ ]:
new_dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
13455,10262.0,-1.161678,1.014845,1.341105,0.219589,-0.399681,-0.792609,0.060908,0.450452,0.744772,...,-0.290013,-0.735224,0.328666,0.410629,-0.247836,0.007369,0.006379,0.007010,19.98,0.0
193359,143238.0,-0.905777,1.242481,-0.716030,-0.646550,0.479189,-0.939751,0.273707,0.552560,-0.567054,...,0.407173,0.937074,-0.300562,0.729079,0.234039,-0.196718,-0.288665,-0.142388,1.79,0.0
139260,119470.0,-0.643736,-0.178902,-0.279128,-0.806155,1.804098,1.499641,0.597049,0.239050,0.243199,...,-0.102520,0.244553,0.544099,-0.592483,-1.084877,0.176266,-0.348630,-0.235414,32.80,0.0
191141,142327.0,-0.679435,0.618923,1.194657,-0.425657,-2.250719,0.751678,-0.570801,-3.343568,-0.617492,...,2.325145,-2.408189,0.156442,0.292784,1.115726,-0.234767,0.407610,0.109090,208.62,0.0
104104,80542.0,1.104597,-0.277470,1.231644,0.634464,-1.254868,-0.380660,-0.761793,0.227249,0.548320,...,0.134066,0.261670,0.036225,0.522854,0.071286,0.323604,-0.008937,0.022038,29.05,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250144,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1.0
250424,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1.0
250430,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1.0
251425,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1.0
251955,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
1.0    423
0.0     25
Name: count, dtype: int64

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
13455    10262.0 -1.161678  1.014845  1.341105  0.219589 -0.399681 -0.792609
193359  143238.0 -0.905777  1.242481 -0.716030 -0.646550  0.479189 -0.939751
139260  119470.0 -0.643736 -0.178902 -0.279128 -0.806155  1.804098  1.499641
191141  142327.0 -0.679435  0.618923  1.194657 -0.425657 -2.250719  0.751678
104104   80542.0  1.104597 -0.277470  1.231644  0.634464 -1.254868 -0.380660
...          ...       ...       ...       ...       ...       ...       ...
250144  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
250424  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
250430  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
251425  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
251955  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
13455   0.060908  0.450452  0.744772  ... -0.193991 -0.290013 -0.735224
193359  0.273707  0.552560 -0.567054  ... -0.339281  0.407173  0.937074
139260  0.597049  0.239050  0.243199  ... -0.635518 -0.102520  0.244553
191141 -0.570801 -3.343568 -0.617492  ... -1.206486  2.325145 -2.408189
104104 -0.761793  0.227249  0.548320  ... -0.129619  0.134066  0.261670
...          ...       ...       ...  ...       ...       ...       ...
250144 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
250424 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
250430 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
251425 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
251955  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
13455   0.328666  0.410629 -0.247836  0.007369  0.006379  0.007010   19.98
193359 -0.300562  0.729079  0.234039 -0.196718 -0.288665 -0.142388    1.79
139260  0.544099 -0.592483 -1.084877  0.176266 -0.348630 -0.235414   32.80
191141  0.156442  0.292784  1.115726 -0.234767  0.407610  0.109090  208.62
104104  0.036225  0.522854  0.071286  0.323604 -0.008937  0.022038   29.05
...          ...       ...       ...       ...       ...       ...     ...
250144  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
250424 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
250430  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
251425 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
251955 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[448 rows x 30 columns]

In [ ]:
print(Y)

13455     0.0
193359    0.0
139260    0.0
191141    0.0
104104    0.0
         ...
250144    1.0
250424    1.0
250430    1.0
251425    1.0
251955    1.0
Name: Class, Length: 448, dtype: float64

Split the data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(448, 30) (358, 30) (90, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
#training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# Accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data:',training_data_accuracy)

Accuracy on Training data: 0.9581005586592178